name: walletconnect_modal_flutter
description: The WalletConnectModal for WalletConnect built using Flutter.
version: 2.1.16
repository: https://github.com/WalletConnect/WalletConnectModalFlutter

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  appcheck: ^1.1.0
  cupertino_icons: ^1.0.8
  event: ^2.1.2
  flutter:
    sdk: flutter
  flutter_keyboard_visibility: ^6.0.0
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  http: ^1.2.0
  json_annotation: ^4.9.0
  logger: ^2.0.2+1
  qr_flutter: ^4.1.0
  shared_preferences: ^2.2.3
  smooth_page_indicator: ^1.1.0
  universal_io: ^2.2.2
  url_launcher: ^6.2.6
  w_common: ^3.0.1
  walletconnect_flutter_v2: ^2.2.3

dev_dependencies:
  build_runner: ^2.4.8
  build_version: ^2.1.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  network_image_mock: ^2.1.1
  

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/help_page/
    - assets/icons/

