name: walletconnect_modal_flutter
description: The WalletConnectModal for WalletConnect built using Flutter.
version: 2.1.1
repository: https://github.com/WalletConnect/WalletConnectModalFlutter

environment:
  sdk: '>=2.17.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  walletconnect_flutter_v2: ^2.1.2
  flutter_svg: ^2.0.6
  qr_flutter: ^4.1.0
  json_annotation: ^4.8.1
  url_launcher: ^6.1.11
  universal_io: ^2.2.0
  w_common: ^3.0.0
  logger: ^1.4.0
  http: ^0.13.6
  freezed_annotation: ^2.2.0
  smooth_page_indicator: ^1.1.0
  event: ^2.1.2
  flutter_keyboard_visibility: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  json_serializable: ^6.7.0
  build_runner: ^2.4.4
  flutter_lints: ^2.0.0
  freezed: ^2.3.5
  mockito: ^5.4.2
  network_image_mock: ^2.1.1
  

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/help_page/
    - assets/icons/

